# This is a basic workflow to help you get started with Actions
# https://github.com/marketplace/actions/free-disk-space-ubuntu
name: dockerhub:2020.0

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string 1:00  weekly,Thursday,1:00 #m h d/m m d/w 
    - cron:  '45 3 * * 5'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Remove unnecessary files
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      -
        name: Build for test
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile20
          push: true
          tags: credocker/creml:check20 

      -
        name: Test
        run: |
          docker run --volume /var/run/docker.sock:/tmp/docker.sock:ro credocker/creml:check20 /cre/ml-test.sh 
      -
        name: Build and push
        id: docker_push
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile20
          push: true
          tags: credocker/creml:2020.0, credocker/creml:latest

